development:
  AWS_ACCESS_KEY_ID: 'PASTE ACCESS ID'
  AWS_SECRET_ACCESS_KEY: 'SECRET KEY'
test:
  AWS_ACCESS_KEY_ID: 'PASTE ACCESS ID'
  AWS_SECRET_ACCESS_KEY: 'SECRET KEY'
production:
  AWS_ACCESS_KEY_ID: 'PASTE ACCESS ID'
  AWS_SECRET_ACCESS_KEY: 'SECRET KEY'
